FROM node:20.8.0
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install @aws-sdk/client-secrets-manager @aws-sdk/client-dynamodb @aws-sdk/credential-provider-env
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start"]